services:
  redis:
    image: redis:7-alpine
    container_name: spring-boot-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - redis-network

  redis-insight:
    image: redis/redisinsight:latest
    container_name: spring-boot-redis-insight
    ports:
      - "5540:5540"
    volumes:
      - ./redisinsight-data:/data
    restart: unless-stopped
    networks:
      - redis-network
    depends_on:
      - redis

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: spring-boot-redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    restart: unless-stopped
    networks:
      - redis-network
    depends_on:
      - redis

volumes:
  redis-data:
    driver: local
  redisinsight-data:
    driver: local

networks:
  redis-network:
    driver: bridge
